/**
 * Enums for the Digital Voucher Ecosystem
 */

export enum UserRole {
  EMPLOYEE = 'EMPLOYEE',
  SELLER = 'SELLER',
  ADMIN = 'ADMIN',
  FINANCE = 'FINANCE',
}

export enum CouponType {
  TEA = 'TEA',
  COFFEE = 'COFFEE',
  SNACK = 'SNACK',
}

export enum LedgerEntryType {
  ISSUANCE = 'ISSUANCE',
  REDEMPTION = 'REDEMPTION',
  TRANSFER_DEBIT = 'TRANSFER_DEBIT',
  TRANSFER_CREDIT = 'TRANSFER_CREDIT',
  REFUND = 'REFUND',
  EXPIRY = 'EXPIRY',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  CONFLICT = 'CONFLICT',
}

export enum BadgeType {
  EARLY_BIRD = 'EARLY_BIRD',
  COFFEE_ADDICT = 'COFFEE_ADDICT',
  SUSTAINABILITY_CHAMPION = 'SUSTAINABILITY_CHAMPION',
  APPRECIATION_STAR = 'APPRECIATION_STAR',
  STREAK_MASTER = 'STREAK_MASTER',
  FIRST_REDEMPTION = 'FIRST_REDEMPTION',
}

export enum NotificationType {
  REDEMPTION_SUCCESS = 'REDEMPTION_SUCCESS',
  TRANSFER_RECEIVED = 'TRANSFER_RECEIVED',
  TRANSFER_SENT = 'TRANSFER_SENT',
  BADGE_EARNED = 'BADGE_EARNED',
  STREAK_WARNING = 'STREAK_WARNING',
  SYNC_CONFLICT = 'SYNC_CONFLICT',
}

export enum BeverageType {
  BLACK_COFFEE = 'BLACK_COFFEE',
  COFFEE_DAIRY = 'COFFEE_DAIRY',
  COFFEE_OAT_SOY = 'COFFEE_OAT_SOY',
  GREEN_TEA = 'GREEN_TEA',
}
